services:
  frontend:
    build:
      context: ./video-game-db-frontend
      dockerfile: Dockerfile
    image: your-dockerhub-username/vgdb-frontend:latest
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - auth-service
      - game-service
      
  game-service:
    build:
      context: ./video-game-db-backend/game-service
      dockerfile: Dockerfile
    image: your-dockerhub-username/vgdb-game:latest
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${GAME_PORT}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    

  
  auth-service:
    build:
      context: ./video-game-db-backend/auth-service
      dockerfile: Dockerfile
    image: your-dockerhub-username/vgdb-auth:latest
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${AUTH_PORT}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}

