name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create env files
      run: |
        # Create root .env for docker-compose
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
        echo "AUTH_PORT=3000" >> .env
        echo "GAME_PORT=3001" >> .env
        echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" >> .env
        echo "DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}" >> .env
        echo "DISCORD_REDIRECT_URI=${{ secrets.DISCORD_REDIRECT_URI }}" >> .env
        echo "CLIENT_ID=${{ secrets.IGDB_CLIENT_ID }}" >> .env
        echo "CLIENT_SECRET=${{ secrets.IGDB_CLIENT_SECRET }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "FRONTEND_URL=http://localhost:5173" >> .env

    - name: Build and push
      run: |
        docker-compose build
        docker-compose push 